# Libraries

In [1]:
import os
os.chdir('C:/Users/msali/Desktop/Python/physics-guided-gwl/src')  # Provide the new path here

In [2]:
from datetime import datetime

In [3]:
from operator import itemgetter
from tqdm import tqdm
import time
from datetime import datetime
import json
from collections import deque
import copy

import numpy as np
import pandas as pd
import geopandas as gpd
import xarray
import rioxarray
import fiona

#import matplotlib
import matplotlib.pyplot as plt

#from rasterio.enums import Resampling
import importlib

import seaborn as sns

In [ ]:
raw_data_dir = ""
main_dir = ""
save_dir = f"{main_dir}/data"
geo_data = f"{main_dir}/data/shapefile"

# Load and Merge Raw Data

This part consist in loading and merging raw ARPA dataset that are divided by years. Column names are left as in the original datasets

In [5]:
wtd_raw_2000_2004 = pd.read_csv(f"{raw_data_dir}/DatiPiezometriciSoggiacenzaFinoAl2004.csv",
              sep = ";",
              dtype={"objectid":'str',
                     "codice_parametro_arpa":'str',
                     "codice_punto":'str',
                     "gwbregcod":'str'})

wtd_raw_2000_2004["data_ora"] = wtd_raw_2000_2004[["data_misura","ora_misura"]].agg(" ".join, axis=1)

wtd_raw_2000_2004 = wtd_raw_2000_2004.astype({"data_ora":'datetime64[ns]'})

wtd_raw_2000_2004 = wtd_raw_2000_2004[["objectid","codice_parametro_arpa","codice_punto","data_ora", "valore_acquisito", "valore_validato", "gwbregcod"]]

In [6]:
wtd_raw_2000_2004

,objectid,codice_parametro_arpa,codice_punto,data_ora,valore_acquisito,valore_validato,gwbregcod
0,1,P00010,00100410001,2001-02-16 00:00:00,3.64,3.64,GWB-S2
1,2,P00010,00100410001,2001-02-16 18:00:00,3.64,3.64,GWB-S2
2,3,P00010,00100410001,2001-02-17 00:00:00,3.64,3.64,GWB-S2
3,4,P00010,00100410001,2001-02-17 06:00:00,3.64,3.64,GWB-S2
4,5,P00010,00100410001,2001-02-17 12:00:00,3.64,3.64,GWB-S2
...,...,...,...,...,...,...,...
328113,3183581,P00010,09603510001,2004-12-29 12:00:00,1.52,1.52,GWB-S1
328114,3183582,P00010,09603510001,2004-12-30 00:00:00,1.54,1.54,GWB-S1
328115,3183583,P00010,09603510001,2004-12-30 12:00:00,1.54,1.54,GWB-S1
328116,3183584,P00010,09603510001,2004-12-31 00:00:00,1.55,1.55,GWB-S1
328117,3183585,P00010,09603510001,2004-12-31 12:00:00,1.56,1.56,GWB-S1

In [7]:
wtd_raw_2005_2012 = pd.read_csv(f"{raw_data_dir}/DatiPiezometriciSoggiacenzaDal2005Al2012.csv",
              sep = ";",
              dtype={"objectid":'str',
                     "codice_parametro_arpa":'str',
                     "codice_punto":'str',
                     "gwbregcod":'str'})

wtd_raw_2005_2012["data_ora"] = wtd_raw_2005_2012[["data_misura","ora_misura"]].agg(" ".join, axis=1)

wtd_raw_2005_2012 = wtd_raw_2005_2012.astype({"data_ora":'datetime64[ns]'})

wtd_raw_2005_2012 = wtd_raw_2005_2012[["objectid","codice_parametro_arpa","codice_punto","data_ora", "valore_acquisito", "valore_validato", "gwbregcod"]]

In [8]:
wtd_raw_2005_2012

,objectid,codice_parametro_arpa,codice_punto,data_ora,valore_acquisito,valore_validato,gwbregcod
0,3287,P00010,00100410001,2005-01-01 00:00:00,4.10,4.10,GWB-S2
1,3288,P00010,00100410001,2005-01-01 12:00:00,4.10,4.10,GWB-S2
2,3289,P00010,00100410001,2005-01-02 00:00:00,4.10,4.10,GWB-S2
3,3290,P00010,00100410001,2005-01-02 12:00:00,4.10,4.10,GWB-S2
4,3291,P00010,00100410001,2005-01-03 00:00:00,4.11,4.11,GWB-S2
...,...,...,...,...,...,...,...
992695,3193658,P00010,09603510001,2012-12-30 08:00:00,1.77,1.77,GWB-S1
992696,3193660,P00010,09603510001,2012-12-30 16:00:00,1.77,1.77,GWB-S1
992697,3193662,P00010,09603510001,2012-12-31 00:00:00,1.77,1.77,GWB-S1
992698,3193663,P00010,09603510001,2012-12-31 08:00:00,1.77,1.77,GWB-S1
992699,3193665,P00010,09603510001,2012-12-31 16:00:00,1.78,1.78,GWB-S1

In [9]:
wtd_raw_2013_2019 = pd.read_csv(f"{raw_data_dir}/DatiPiezometriciSoggiacenzaDal2013Al2019.csv",
              sep = ";",
              dtype={"objectid":'str',
                     "codice_parametro_arpa":'str',
                     "codice_punto":'str',
                     "gwbregcod":'str'})

wtd_raw_2013_2019["data_ora"] = wtd_raw_2013_2019[["data_misura","ora_misura"]].agg(" ".join, axis=1)

wtd_raw_2013_2019 = wtd_raw_2013_2019.astype({"data_ora":'datetime64[ns]'})

wtd_raw_2013_2019 = wtd_raw_2013_2019[["objectid","codice_parametro_arpa","codice_punto","data_ora", "valore_acquisito", "valore_validato", "gwbregcod"]]

In [10]:
wtd_raw_2013_2019

,objectid,codice_parametro_arpa,codice_punto,data_ora,valore_acquisito,valore_validato,gwbregcod
0,13438,P00010,00100410001,2013-01-01 00:00:00,4.14,4.14,GWB-S2
1,13440,P00010,00100410001,2013-01-01 08:00:00,4.14,4.14,GWB-S2
2,13442,P00010,00100410001,2013-01-01 16:00:00,4.14,4.14,GWB-S2
3,13443,P00010,00100410001,2013-01-02 00:00:00,4.14,4.14,GWB-S2
4,13445,P00010,00100410001,2013-01-02 08:00:00,4.14,4.14,GWB-S2
...,...,...,...,...,...,...,...
762425,3204237,P00010,09603510001,2019-12-30 08:00:00,1.68,1.68,GWB-S1
762426,3204239,P00010,09603510001,2019-12-30 16:00:00,1.69,1.69,GWB-S1
762427,3204241,P00010,09603510001,2019-12-31 00:00:00,1.70,1.70,GWB-S1
762428,3204242,P00010,09603510001,2019-12-31 08:00:00,1.70,1.70,GWB-S1
762429,3204244,P00010,09603510001,2019-12-31 16:00:00,1.70,1.70,GWB-S1

In [11]:
wtd_raw_2020_2024 = pd.read_csv(f"{raw_data_dir}/DatiPiezometriciSoggiacenzaDal2020.csv",
              sep = ";",
              dtype={"objectid":'str',
                     "codice_parametro_arpa":'str',
                     "codice_punto":'str',
                     "dataora_misura":'str',
                     "gwbregcod":'str'})

wtd_raw_2020_2024 = wtd_raw_2020_2024.astype({"dataora_misura":'datetime64[ns]'})

wtd_raw_2020_2024 = wtd_raw_2020_2024[["objectid","codice_parametro_arpa","codice_punto","dataora_misura", "valore_acquisito", "valore_validato", "codice_corpo_idrico"]]

In [12]:
wtd_raw_2020_2024

,objectid,codice_parametro_arpa,codice_punto,dataora_misura,valore_acquisito,valore_validato,codice_corpo_idrico
0,22201,P00010,00100410001,2020-01-01 00:00:00,3.66,3.66,GWB-S2
1,22202,P00010,00100410001,2020-01-01 08:00:00,3.66,3.66,GWB-S2
2,22204,P00010,00100410001,2020-01-01 16:00:00,3.66,3.66,GWB-S2
3,22206,P00010,00100410001,2020-01-02 00:00:00,3.67,3.67,GWB-S2
4,22207,P00010,00100410001,2020-01-02 08:00:00,3.67,3.67,GWB-S2
...,...,...,...,...,...,...,...
436355,3312580,P00010,09603510001,2024-12-30 08:00:00,2.06,2.06,GWB-S1
436356,3312581,P00010,09603510001,2024-12-30 16:00:00,2.06,2.06,GWB-S1
436357,3312582,P00010,09603510001,2024-12-31 00:00:00,2.06,2.06,GWB-S1
436358,3312584,P00010,09603510001,2024-12-31 08:00:00,2.06,2.06,GWB-S1
436359,3312585,P00010,09603510001,2024-12-31 16:00:00,2.06,2.06,GWB-S1

In [13]:
wtd_raw_2020_2024.columns = ['objectid', 'codice_parametro_arpa', 'codice_punto', 'data_ora', 'valore_acquisito', 'valore_validato', 'gwbregcod']

In [14]:
wtd_raw_2020_2024

,objectid,codice_parametro_arpa,codice_punto,data_ora,valore_acquisito,valore_validato,gwbregcod
0,22201,P00010,00100410001,2020-01-01 00:00:00,3.66,3.66,GWB-S2
1,22202,P00010,00100410001,2020-01-01 08:00:00,3.66,3.66,GWB-S2
2,22204,P00010,00100410001,2020-01-01 16:00:00,3.66,3.66,GWB-S2
3,22206,P00010,00100410001,2020-01-02 00:00:00,3.67,3.67,GWB-S2
4,22207,P00010,00100410001,2020-01-02 08:00:00,3.67,3.67,GWB-S2
...,...,...,...,...,...,...,...
436355,3312580,P00010,09603510001,2024-12-30 08:00:00,2.06,2.06,GWB-S1
436356,3312581,P00010,09603510001,2024-12-30 16:00:00,2.06,2.06,GWB-S1
436357,3312582,P00010,09603510001,2024-12-31 00:00:00,2.06,2.06,GWB-S1
436358,3312584,P00010,09603510001,2024-12-31 08:00:00,2.06,2.06,GWB-S1
436359,3312585,P00010,09603510001,2024-12-31 16:00:00,2.06,2.06,GWB-S1

In [15]:
# Merging
wtd_raw = pd.concat([wtd_raw_2000_2004,
                    wtd_raw_2005_2012,
                    wtd_raw_2013_2019,
                    wtd_raw_2020_2024], ignore_index=True)

wtd_raw = wtd_raw.set_index(['data_ora','codice_punto'])
wtd_raw.index.rename(['data_misura','codice_punto'], inplace = True)
wtd_raw

,,objectid,codice_parametro_arpa,valore_acquisito,valore_validato,gwbregcod
data_misura,codice_punto,,,,,
2001-02-16 00:00:00,00100410001,1,P00010,3.64,3.64,GWB-S2
2001-02-16 18:00:00,00100410001,2,P00010,3.64,3.64,GWB-S2
2001-02-17 00:00:00,00100410001,3,P00010,3.64,3.64,GWB-S2
2001-02-17 06:00:00,00100410001,4,P00010,3.64,3.64,GWB-S2
2001-02-17 12:00:00,00100410001,5,P00010,3.64,3.64,GWB-S2
...,...,...,...,...,...,...
2024-12-30 08:00:00,09603510001,3312580,P00010,2.06,2.06,GWB-S1
2024-12-30 16:00:00,09603510001,3312581,P00010,2.06,2.06,GWB-S1
2024-12-31 00:00:00,09603510001,3312582,P00010,2.06,2.06,GWB-S1
2024-12-31 08:00:00,09603510001,3312584,P00010,2.06,2.06,GWB-S1
2024-12-31 16:00:00,09603510001,3312585,P00010,2.06,2.06,GWB-S1

In [16]:
#Saving
wtd_raw.to_csv(f"{raw_data_dir}/water_table_depth_1996_2024_raw.csv", index = True)

In [ ]:
wtd_raw.loc

In [17]:
wtd_ds = wtd_raw.drop(["objectid","valore_acquisito","gwbregcod","codice_parametro_arpa"], axis = 1).rename({"valore_validato":"wtd"}, axis = 1)
wtd_ds.index = wtd_ds.index.set_names("date", level=0)
wtd_ds.index = wtd_ds.index.set_names("sensor_id", level=1)

In [18]:
wtd_ds

                                  wtd
date                sensor_id
2001-02-16 00:00:00 00100410001  3.64
2001-02-16 18:00:00 00100410001  3.64
2001-02-17 00:00:00 00100410001  3.64
2001-02-17 06:00:00 00100410001  3.64
2001-02-17 12:00:00 00100410001  3.64
...                               ...
2024-12-30 08:00:00 09603510001  2.06
2024-12-30 16:00:00 09603510001  2.06
2024-12-31 00:00:00 09603510001  2.06
2024-12-31 08:00:00 09603510001  2.06
2024-12-31 16:00:00 09603510001  2.06

[2519608 rows x 1 columns]

In [19]:
#Saving
wtd_ds.to_csv(f"{raw_data_dir}/water_table_depth_1996_2024.csv", index = True)

In [20]:
len(wtd_raw.index.get_level_values(1).unique())

127

# Deep Piezometers

In [35]:
deep_wtd_raw = wtd_raw[wtd_raw["gwbregcod"].str.contains(r"GWB-P", regex=True, na=False)]
deep_wtd_raw

,,objectid,codice_parametro_arpa,valore_acquisito,valore_validato,gwbregcod
data_misura,codice_punto,,,,,
2005-04-14 00:00:00,00108610002,351168,P00010,13.22,13.22,GWB-P2
2005-04-14 18:00:00,00108610002,351169,P00010,13.35,13.35,GWB-P2
2005-04-15 00:00:00,00108610002,351170,P00010,13.22,13.22,GWB-P2
2005-04-15 06:00:00,00108610002,351171,P00010,13.30,13.30,GWB-P2
2005-04-15 12:00:00,00108610002,351172,P00010,13.96,13.96,GWB-P2
...,...,...,...,...,...,...
2024-12-30 08:00:00,00414310003,2251082,P00010,2.31,2.31,GWB-P3
2024-12-30 16:00:00,00414310003,2251083,P00010,2.31,2.31,GWB-P3
2024-12-31 00:00:00,00414310003,2251085,P00010,2.32,2.32,GWB-P3
2024-12-31 08:00:00,00414310003,2251087,P00010,2.31,2.31,GWB-P3
2024-12-31 16:00:00,00414310003,2251090,P00010,2.31,2.31,GWB-P3

In [37]:
deep_wtd_raw.index.get_level_values(1).unique()

Index(['00108610002', '00113010002', '00127210004', '00105910003',
       '00127210006', '00131410002', '00408910003', '00414310003'],
      dtype='object', name='codice_punto')

# Spatial Metadata and ROI

In [21]:
underground_sensors_shp = gpd.read_file(f"{geo_data}/underground_wtd_sensor_roi.shp") 
underground_sensors_shp

,sensor_id,wb_id,loc_name,munic,loc,sart_date,end_date,gw_type,geometry
0,00107010001,GWB-S5b,P15 Cavour,Cavour,lato cimitero,2009-01-01,None,Shallow,POINT (7.38103 44.78737)
1,00104110001,GWB-S5a,P24 Buriasco,Buriasco,davanti cimitero,2009-01-01,None,Shallow,POINT (7.41560 44.87792)
2,00105110001,GWB-S3b,P20 Candiolo,Candiolo,davanti cimitero,2009-01-01,None,Shallow,POINT (7.59870 44.95656)
3,00127210003,GWB-S3b,SI2 Torino-Dora Riparia,Torino,passeggiata lungodora ponte Washington,2009-01-01,None,Shallow,POINT (7.71871 45.07816)
4,00403410001,GWB-S6,P1 Busca,Busca,Area verde Fraz. S.Rocco,2009-01-01,None,Shallow,POINT (7.48982 44.50843)
5,00119710001,GWB-S4a,P22 Poirino,Poirino,"Parcheggio cimitero comunale, V.le delle Rimem...",2009-01-01,None,Shallow,POINT (7.84773 44.92544)
6,00105910002,GWB-S5a,TF2 Tetto Frati Carmagnola,Carmagnola,C/o Centro Sperimentale della FacoltÃ di Agraria,2009-01-01,None,Shallow,POINT (7.68685 44.88793)
7,00421510001,GWB-S6,P6 Savigliano,Savigliano,"c/o Stadio ""Ottavio Morino"", V.le Gozzano",2009-01-01,None,Shallow,POINT (7.65242 44.64596)
8,00422510001,GWB-S6,P2 Tarantasca,Tarantasca,"Parcheggio cimitero Fraz. S.Cristina, Via R. S...",2009-01-01,None,Shallow,POINT (7.53227 44.51818)
9,00404110001,GWB-S6,P12 Caramagna Piemonte,Caramagna Piemonte,davanti cimitero,2009-01-01,None,Shallow,POINT (7.73514 44.78702)
10,00117110001,GWB-S3b,P10 Orbassano,Orbassano,piazzale campo sportivo,2009-01-01,None,Shallow,POINT (7.53446 45.01630)
11,00112710001,GWB-S5a,P19 La Loggia,La Loggia,"Zona industriale, parcheggio Via D. Vittorio",2009-01-01,None,Shallow,POINT (7.67314 44.96300)
12,00104810001,GWB-S4a,P40 Area verde via Triberti,Cambiano,Via CavagliÃ,2019-01-01,None,Shallow,POINT (7.77064 44.96545)
13,00126010001,GWB-S5a,P17 Scalenghe,Scalenghe,"Spiazzo recintato, Via Monviso",2009-01-01,None,Shallow,POINT (7.49480 44.88944)
14,00109010001,GWB-S3b,P18 Collegno,Collegno,su strada in via della Piombia,2009-01-01,None,Shallow,POINT (7.57467 45.09390)
15,00105910001,GWB-S4b,P16 Carmagnola,Carmagnola,"Peso pubblico, P.za della Concordia",2009-01-01,None,Shallow,POINT (7.72379 44.86086)
16,00407810001,GWB-S6,T1 Cuneo,Cuneo,Parcheggio campo sportivo Fraz. Madonna dell'Olmo,2009-01-01,None,Shallow,POINT (7.53722 44.41863)
17,00127210005,GWB-S3b,PU Palazzo Unico Regione,Torino,Via Nizza 330,2019-01-01,None,Shallow,POINT (7.66369 45.02454)
18,00425010001,GWB-S6,P5 Vottignasco,Vottignasco,"c/o Cimitero comunale, Via Saluzzo",2009-01-01,None,Shallow,POINT (7.57503 44.57012)
19,00402910001,GWB-S6,P11 Bra,Bra,"Parcheggio cimitero urbano, C.so Monviso",2009-01-01,None,Shallow,POINT (7.84573 44.68882)
20,00408910002,GWB-S6,P23 Fossano (Murazzo),Fossano,davanti cimitero localitÃ Murazzo,2009-01-01,None,Shallow,POINT (7.64965 44.48904)
21,00127210001,GWB-S3b,P26 Torino piazza d'Armi,Torino,"Lato nord giardino P.za d'Armi, C.so Montelungo",2009-01-01,None,Shallow,POINT (7.65555 45.05100)
22,00414310002,GWB-S6,P14/1 Moretta,Moretta,c/o Campo sportivo,2009-01-01,None,Shallow,POINT (7.52928 44.76678)
23,00121510001,GWB-S4a,P39 Aiuola pubblica,Riva presso Chieri,Via Grena - Fraz. S. Giovanni,2019-01-01,None,Shallow,POINT (7.89483 45.00558)
24,00417910001,GWB-S6,P13 Racconigi,Racconigi,Giardino pubblico Via B. Murialdo angolo Via S...,2009-01-01,None,Shallow,POINT (7.68794 44.77265)
25,00401210001,GWB-S5b,P8 Barge,Barge,"Piazzale cimitero comunale, Via Villafranca",2009-01-01,None,Shallow,POINT (7.33948 44.73118)
26,00405910001,GWB-S6,Piezometro CVN,Cavallermaggiore,Via Monasterolo 21,2009-01-01,None,Shallow,POINT (7.64029 44.69885)
27,00408910001,GWB-S6,P4 Fossano,Fossano,"Lato nord cimitero comunale, Str. vicinale del...",2009-01-01,None,Shallow,POINT (7.72640 44.56782)
28,00421710001,GWB-S6,P9 Scarnafigi,Scarnafigi,isola ecologica vicina al cimitero,2009-01-01,None,Shallow,POINT (7.56770 44.68958)
29,00103510001,GWB-S5b,P45 Bricherasio,Bricherasio,Piazzale cimitero,2009-01-01,None,Shallow,POINT (7.30850 44.82984)
30,00131010001,GWB-S5a,P7 Virle Piemonte,Virle Piemonte,retro cimitero,2009-01-01,None,Shallow,POINT (7.56489 44.86888)

In [22]:
wtd_ds

                                  wtd
date                sensor_id
2001-02-16 00:00:00 00100410001  3.64
2001-02-16 18:00:00 00100410001  3.64
2001-02-17 00:00:00 00100410001  3.64
2001-02-17 06:00:00 00100410001  3.64
2001-02-17 12:00:00 00100410001  3.64
...                               ...
2024-12-30 08:00:00 09603510001  2.06
2024-12-30 16:00:00 09603510001  2.06
2024-12-31 00:00:00 09603510001  2.06
2024-12-31 08:00:00 09603510001  2.06
2024-12-31 16:00:00 09603510001  2.06

[2519608 rows x 1 columns]

In [23]:
wtd_ds_subset = wtd_ds.loc[pd.IndexSlice[:,underground_sensors_shp["sensor_id"]],:]
wtd_ds_subset = wtd_ds_subset.sort_values(by='date')
wtd_ds_subset

                                    wtd
date                sensor_id
1996-01-01 08:30:00 00405910001   1.700
1996-01-04 16:00:00 00405910001   1.700
1996-01-07 13:30:00 00405910001   1.700
1996-01-10 15:00:00 00405910001   1.600
1996-01-13 09:00:00 00405910001   1.500
...                                 ...
2024-12-31 16:00:00 00112710001   3.890
                    00422510001  24.488
                    00127210003   7.950
                    00421710001   5.852
                    00131010001   2.556

[626773 rows x 1 columns]

In [24]:
wtd_ds_subset = wtd_ds_subset.reset_index().set_index(["date"])
wtd_ds_subset = wtd_ds_subset.groupby([pd.Grouper(freq="D", label = "left"), "sensor_id"]).mean()
wtd_ds_subset = wtd_ds_subset.reset_index()
wtd_ds_subset

             date    sensor_id        wtd
0      1996-01-01  00405910001   1.700000
1      1996-01-04  00405910001   1.700000
2      1996-01-07  00405910001   1.700000
3      1996-01-10  00405910001   1.600000
4      1996-01-13  00405910001   1.500000
...           ...          ...        ...
192393 2024-12-31  00414310002   2.200000
192394 2024-12-31  00421510001   3.980000
192395 2024-12-31  00421710001   5.846667
192396 2024-12-31  00422510001  24.485333
192397 2024-12-31  00425010001   4.380000

[192398 rows x 3 columns]

In [25]:
wtd_ds_subset = wtd_ds_subset.set_index(['date', 'sensor_id'])

In [26]:
wtd_ds_subset

                              wtd
date       sensor_id
1996-01-01 00405910001   1.700000
1996-01-04 00405910001   1.700000
1996-01-07 00405910001   1.700000
1996-01-10 00405910001   1.600000
1996-01-13 00405910001   1.500000
...                           ...
2024-12-31 00414310002   2.200000
           00421510001   3.980000
           00421710001   5.846667
           00422510001  24.485333
           00425010001   4.380000

[192398 rows x 1 columns]

# Insert missing dates

In [27]:
min_date = str(wtd_ds_subset.index.get_level_values(0).min())
max_date = str(wtd_ds_subset.index.get_level_values(0).max())

filled_date_range = pd.date_range(min_date, max_date, freq="D")

In [28]:
wtd_ds_subset.index.get_level_values(1).unique()

Index(['00405910001', '00408910001', '00407810001', '00105910001',
       '00112710001', '00126010001', '00417910001', '00422510001',
       '00127210001', '00103510001', '00401210001', '00403410001',
       '00421510001', '00119710001', '00402910001', '00425010001',
       '00105910002', '00414310002', '00109010001', '00127210003',
       '00117110001', '00131010001', '00408910002', '00421710001',
       '00104110001', '00107010001', '00105110001', '00404110001',
       '00121510001', '00104810001', '00127210005'],
      dtype='object', name='sensor_id')

In [29]:
filled_wtd_ds_subset = wtd_ds_subset.reindex(pd.MultiIndex.from_product((pd.DatetimeIndex(filled_date_range),
                            wtd_ds_subset.index.get_level_values(1).unique()), names=["date", "sensor_id"]),
                     fill_value=np.nan)

In [30]:
filled_wtd_ds_subset

                             wtd
date       sensor_id
1996-01-01 00405910001  1.700000
           00408910001       NaN
           00407810001       NaN
           00105910001       NaN
           00112710001       NaN
...                          ...
2024-12-31 00105110001  2.916667
           00404110001       NaN
           00121510001  9.756667
           00104810001  1.646667
           00127210005       NaN

[328383 rows x 1 columns]

In [31]:
# Check
print("Old values are the same? ", filled_wtd_ds_subset.loc[wtd_ds_subset.index].equals(wtd_ds_subset))

print("New dates are nan? ", filled_wtd_ds_subset.loc[~filled_wtd_ds_subset.index.isin(wtd_ds_subset.index)].isna().all())

Old values are the same?  True
New dates are nan?  wtd    True
dtype: bool

# Saving

In [32]:
filled_wtd_ds_subset.to_csv(f"{save_dir}/dataset_wtd_roi_1996_2024.csv", index = True)